def build_receipt_items(
    no_s_pizza,
    no_m_pizza,
    no_l_pizza,
    no_s_burger,
    no_m_burger,
    no_l_burger,
    s_butter,
    no_butter,
    s_wrap,
    no_wrap,
    no_karak,
    no_green,
    no_black,
    no_latte,
    no_cappuccino,
    no_americano,
    no_s_milk,
    no_m_milk,
    no_l_milk,
    no_s_melon,
    no_m_melon,
    no_l_melon,
    no_ice,
    no_gulab,
    no_cheese,
    no_kunafa,
):
    return [
        {'item': 'Pizza', 'quantity': no_s_pizza, 'size': 'Small', 'total_cost': no_s_pizza * 10.00},
        {'item': 'Pizza', 'quantity': no_m_pizza, 'size': 'Medium', 'total_cost': no_m_pizza * 15.00},
        {'item': 'Pizza', 'quantity': no_l_pizza, 'size': 'Large', 'total_cost': no_l_pizza * 20.00},
        {'item': 'Burger', 'quantity': no_s_burger, 'size': 'Small', 'total_cost': no_s_burger * 4.00},
        {'item': 'Burger', 'quantity': no_m_burger, 'size': 'Medium', 'total_cost': no_m_burger * 8.00},
        {'item': 'Burger', 'quantity': no_l_burger, 'size': 'Large', 'total_cost': no_l_burger * 12.00},
        {'item': f'''Butter Chicken {s_butter}''', 'quantity': no_butter, 'size': 'N/A', 'total_cost': no_butter * 14.00},
        {'item': f'''Grilled Wrap{s_wrap}''', 'quantity': no_wrap, 'size': 'N/A', 'total_cost': no_wrap * 5.00},
        {'item': 'Karak', 'quantity': no_karak, 'size': 'N/A', 'total_cost': no_karak * 1.50},
        {'item': 'Green Tea', 'quantity': no_green, 'size': 'N/A', 'total_cost': no_green * 1.00},
        {'item': 'Black Tea', 'quantity': no_black, 'size': 'N/A', 'total_cost': no_black * 0.50},
        {'item': 'Latte', 'quantity': no_latte, 'size': 'N/A', 'total_cost': no_latte * 2.00},
        {'item': 'Cappuccino', 'quantity': no_cappuccino, 'size': 'N/A', 'total_cost': no_cappuccino * 2.50},
        {'item': 'Americano', 'quantity': no_americano, 'size': 'N/A', 'total_cost': no_americano * 3.00},
        {'item': 'Choclocate Milk', 'quantity': no_s_milk, 'size': 'Medium', 'total_cost': no_s_milk * 7.50},
        {'item': 'Choclocate Milk', 'quantity': no_m_milk, 'size': 'Medium', 'total_cost': no_m_milk * 9.00},
        {'item': 'Choclocate Milk', 'quantity': no_l_milk, 'size': 'Medium', 'total_cost': no_l_milk * 12.00},
        {'item': 'Watermelon Juice', 'quantity': no_s_melon, 'size': 'Medium', 'total_cost': no_s_melon * 6.00},
        {'item': 'Watermelon Juice', 'quantity': no_m_melon, 'size': 'Medium', 'total_cost': no_m_melon * 7.50},
        {'item': 'Watermelon Juice', 'quantity': no_l_melon, 'size': 'Medium', 'total_cost': no_l_melon * 8.00},
        {'item': 'Ice Cream', 'quantity': no_ice, 'size': 'N/A', 'total_cost': no_ice * 1.00},
        {'item': 'Gulab Jamun', 'quantity': no_gulab, 'size': 'N/A', 'total_cost': no_gulab * 4.00},
        {'item': 'Cheese Cake', 'quantity': no_cheese, 'size': 'N/A', 'total_cost': no_cheese * 6.00},
        {'item': 'Kunafa', 'quantity': no_kunafa, 'size': 'N/A', 'total_cost': no_kunafa * 7.00},
    ]
